### ISSUE TITLE
Write deterministic epidemic models

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#1]
This issue tracks the development of the epidemic models.

- [x] #12 
- [x] #14
- [x] #17
- [x] #18
- [x] #19
- [x] #20

**Comment by bryce-carson** [comment]
@ashokkrish, I marked the two models that you created tracking issues for (this is fairly intuitive, hey?) as incomplete, but then they disappeared from this list. I think that happened because when you created issues for them, you also checked them as complete. There was probably a time delay of some sort (but usually tasks don't disappear from the list).  
  
Should the models tracked by issues #2 and #3 be added back to the list of tasks?

**Comment by ashokkrish** [comment]
@bryce-carson I am really sorry. This is my first time using GitHub issues. I was trying to suggest issues #2 and #3 can be removed from the list. I edited the list and deleted them. Sorry about that.

**Comment by bryce-carson** [comment]
Once Tobias joins the repository as a collaborator, confirming his GitHub username with us, I'll make Tobias an assignee of this issue again. I'm not sure that "Toby-exe" was his GitHub username; he does use that as his Discord username though, so I don't think I truly added the wrong person as an assignee.

**Comment by ashokkrish** [comment]
@Toby-exe is already a collaborator

**Comment by Toby-exe** [comment]
This is my correct account

**Comment by bryce-carson** [comment]
> @Toby-exe is already a collaborator

Thanks for confirming that. I was unsure because the username doesn't currently appear in the list of _Collaborators_. I'm guessing it is because Tobias hasn't made any commits to the repository yet that he doesn't appear in the list yet.

**Comment by bryce-carson** [comment]
> @bryce-carson I am really sorry. This is my first time using GitHub issues. I was trying to suggest issues #2 and #3 can be removed from the list. I edited the list and deleted them. Sorry about that.

That's alright! I began with no knowledge of it one day too. :) It's fun to use, really. You'll enjoy it soon enough!  
  
No worries about removing them from the list. I'm surprised you were able to edit the list in that manner, actually. I suppose you might have been able to edit my comment because you're the administrator of the repository, but I didn't think other users had that level of power over another's comments. In other projects I need to wait for the user who makes a comment with a task list to edit the list themselves (I think).  
  
Anyway, thanks. I'll close issues #2 and #3, since you've indicated we don't need to implement those. When I wrote the model abbreviations I just threw compartment letters at the screen, really. Those two didn't stick! :)

**Comment by bryce-carson** [comment]
I've tried to link the project I created to this repository, but it doesn't seem to want to appear in the search list, even as I changed the visibility of the project to public. 🤷

@ashokkrish, can you navigate to the "Projects" tab of the repository and see if you are able to add that project which now has a hyperlink above this comment? (there is a "trail" or timeline that you can follow, which connects the rectangle of every comment and status update on the left-hand side.) Thanks!

**Comment by ashokkrish** [comment]
I don't see the hyperlinked project at all. Please advice.

**Comment by Toby-exe** [comment]
![Image](https://github.com/ashokkrish/episim/assets/104709648/0a8776d8-e0b8-4a3b-ac91-038c98944a4f)

@ashokkrish Its right above Bryce's most recent comment

**Comment by bryce-carson** [comment]
> This issue tracks the development of the epidemic models.
>
>     * [ ] ...
> 
>     * [ ]  @ashokkrish says no more models should be added to the above list items.

@ashokkrish, if there are no other models you wish us to implement at this time (other than the ones which are stochastic), can you check off that task? I tagged you, implying you should check it off if all the models you wanted are in the list. No worries. :)

**Comment by bryce-carson** [comment]
> > This issue tracks the development of the epidemic models.
> > ```
> > * [ ] ...
> > 
> > * [ ]  @ashokkrish says no more models should be added to the above list items.
> > ```
> 
> @ashokkrish, if there are no other models you wish us to implement at this time (other than the ones which are stochastic), can you check off that task? I tagged you, implying you should check it off if all the models you wanted are in the list. No worries. :)

This is no longer relevant. We will make a new tracking issue for additional model types.
