### ISSUE TITLE
Why was the "Run Simulation" button was removed?

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#102]
In the recent update the **Run Simulation** button has disappeared. There are certain benefits of this button. Would it be too difficult to bring it back?

**Comment by bryce-carson** [comment]
> In the recent update the **Run Simulation** button has disappeared. There are certain benefits of this button. Would it be too difficult to bring it back?

The only benefit is to re-run stochastic simulations.

Your other requests for the application were best served with full reactivity, which I have just finished working on and debugged (as best as I can; it's a complex topic). Having the output panel hidden whenever any input value changes, which I have interpreted as "don't show plots defined by outdated input widget values," is _the essence of reactivity_, **and the essence of Shiny.**

It's not a good idea to bring it back. I realized that what you're looking for in the Episim application really is reactivity, so I implemented that. When the model is stochastic, any time the input changes it will likewise re-run the simulation. The challenge, which is not a mighty one, is to let the user re-run a stochastic simulation on-demand. That's actually trivially easy!

I have implemented a button which is only apparent when the simulation is stochastic (the user selected this option). This button simply increments a counter which is used---but ignored--- in the reactive expression that runs the model and generates the plots. Using a counter like this, the user is able to press the button, which increases the count, invalidates the reactive value depending on---but ignoring the value of--the counter and causes the model to re-run. This is the same, in effect, as the button and all of the imperative-style observability used before, but much more brief and in-step with the principles of reactive programming in Shiny.

With this in mind, Ashok, I'm going to close this issue when I push my code today (which implements this).
