### ISSUE TITLE
Opening hyperlinks in a new tab

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#103]
@Toby-exe 

I would the following to open in a new tab window rather than the same application windows. Could you take care of this Tobi?

# 1
<img width="34" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/334ee1db-ee26-4aae-8bd8-e711ea14b8ae">

# 2

![image](https://github.com/ashokkrish/episim/assets/410949/bb0c68da-db10-4bb0-bf4f-c76ee8eb5379)

# 3

<img width="161" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/88cc48a4-9950-4817-b470-9bf72134b1c8">

**Comment by Toby-exe** [comment]
Resolved in 62a8bee1a2cb8c11e209734ff9f3985db81d6eec

**Comment by Toby-exe** [comment]
Resolved in 62a8bee1a2cb8c11e209734ff9f3985db81d6eec
