### ISSUE TITLE
Line color mismatch

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#106]
@Toby-exe 

A plot for the SIR model with all compartments looks like this

<img width="789" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/dae86f3c-265d-415c-b31f-703b45c3dbe9">

where Susceptible is Purple, Infected is Green and Recovered is Red.

However the plots for individual compartments looks like this

<img width="794" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/876920fa-2db8-41b3-9a96-1a930205e3eb">

where Susceptible is Green, Infected is Red and Recovered is Purple.

The line colours need to be consistent.

**Comment by Toby-exe** [comment]
fixed in f150cd77ebc13b24957c34d815ef20584d15803d
