### ISSUE TITLE
Hide `Output Summary` in the main panel for Stochastic model 

### ISSUE THREAD

**Issue by kle6951** [ashokkrish/episim#114]

**Comment by kle6951** [comment]
The `Output summary` tab panel is now hidden for all stochastic models.

**Comment by ashokkrish** [comment]
@bryce-carson @kle6951 @Toby-exe 

**For a Stochastic model the Output Summary tabPanel should be be hidden.**

**Comment by bryce-carson** [comment]
> @bryce-carson @kle6951 @Toby-exe 
> 
> **For a Stochastic model the Output Summary tabPanel should be be hidden.**

Why is that?

Can do, regardless of why.

**Comment by ashokkrish** [comment]
> > @bryce-carson @kle6951 @Toby-exe
> > **For a Stochastic model the Output Summary tabPanel should be be hidden.**
> 
> Why is that?
> 
> Can do, regardless of why.

Unlike the Deterministic case here the simulation is run a bunch of times (n_steps) and each output is different from the other. Unless the n_steps = 1 it doesn't make sense to print the output summary. I would like this tabPanel hidden for now. Khanh had closed this issue as completed but I reopened it because now it is showing up.

**Comment by bryce-carson** [comment]
> > > @bryce-carson @kle6951 @Toby-exe
> > > **For a Stochastic model the Output Summary tabPanel should be be hidden.**
> > 
> > Why is that?
> > 
> > Can do, regardless of why.
> 
> Unlike the Deterministic case here the simulation is run a bunch of times (n_steps) and each output is different from the other. Unless the n_steps = 1 it doesn't make sense to print the output summary. I would like this tabPanel hidden for now. Khanh had closed this issue as completed but I reopened it because now it is showing up.

What about reporting the mean value per timestep? The information shown in the plots should be similarly available, in my opinion.

**Comment by ashokkrish** [comment]
> > > > @bryce-carson 
> What about reporting the mean value per timestep? The information shown in the plots should be available in a tabular format, similarly to the deterministic simulations, in my opinion.

Yes, that's where I was going with, an output summary of the **average of runs** but in the interest of time I just wanted it hidden and deal with is later. I would imagine it takes a considerable amount of time to implement it so decided to hide it for now.
