### ISSUE TITLE
Toggling to Stochastic models generates this error

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#119]
<img width="348" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/dc7a3471-d51c-4d2e-8018-8b7e13695438">

```
Warning: Error in <Anonymous>: argument "vitalDynamics" is missing, with no default
  146: do.call
  135: <Anonymous> [C:\Users\ashok\Desktop\spatialEpisim2022\episim\R\mathematicalModelHTML_paste.R#31]
  114: <reactive:renderModel> [C:\Users\ashok\Desktop\spatialEpisim2022\episim/server.R#149]
   98: renderModel
   97: renderUI
   96: func
   83: renderFunc
   82: output$outputPanel
    1: shiny::runApp
```

**Comment by kle6951** [comment]
@ashokkrish I am inspecting the reason that causes this error. Since the way all models were implemented before, the vital dynamic variable must be passed to the solver function every time. Right now, Tobias is working on setting up the plot and modifying the `server.R`. Therefore, this error will be fixed soon.

**Comment by ashokkrish** [comment]
> @ashokkrish I am inspecting the reason that causes this error. Since the way all models were implemented before, the vital dynamic variable must be passed to the solver function every time. Right now, Tobias is working on setting up the plot and modifying the `server.R`. Therefore, this error will be fixed soon.

Is it possible to set the mu_B and mu_D to zero in the solvers?

**Comment by kle6951** [comment]
> > @ashokkrish I am inspecting the reason that causes this error. Since the way all models were implemented before, the vital dynamic variable must be passed to the solver function every time. Right now, Tobias is working on setting up the plot and modifying the `server.R`. Therefore, this error will be fixed soon.
> 
> Is it possible to set the mu_B and mu_D to zero in the solvers?

Yes, we can. I am working on fixing this issue.

**Comment by ashokkrish** [comment]
> > > @ashokkrish I am inspecting the reason that causes this error. Since the way all models were implemented before, the vital dynamic variable must be passed to the solver function every time. Right now, Tobias is working on setting up the plot and modifying the `server.R`. Therefore, this error will be fixed soon.
> > 
> > 
> > Is it possible to set the mu_B and mu_D to zero in the solvers?
> 
> Yes, we can. I am working on fixing this issue.

I might suggest let's leave the vital dynamics as is but set mu_B and mu_D to zero and the user cannot change this value at all.

**Comment by kle6951** [comment]
> > > > @ashokkrish I am inspecting the reason that causes this error. Since the way all models were implemented before, the vital dynamic variable must be passed to the solver function every time. Right now, Tobias is working on setting up the plot and modifying the `server.R`. Therefore, this error will be fixed soon.
> > > 
> > > 
> > > Is it possible to set the mu_B and mu_D to zero in the solvers?
> > 
> > 
> > Yes, we can. I am working on fixing this issue.
> 
> I might suggest let's leave the vital dynamics as is but set mu_B and mu_D to zero and the user cannot change this value at all.

Right now, we have separate solver functions for the stochastic, so the solver functions for the stochastic won't need the `mu` value. Therefore, the `mu` value won't be passed to this solver. Yesterday, Tobias showed me the graph when he uses the solver function for uniform stochastic, there isn't any error. 

_For now, I'll leave this issue open and close it once Tobias pushes his code. We will look into this issue again_
