### ISSUE TITLE
`n_steps` is not available in stochastic_binomial_vitalDynamic.R

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#124]
```
Error in simulate_SI(timesteps, population, susceptible, infected, recovered,  : 
  object 'n_steps' not found
```

https://github.com/ashokkrish/episim/blob/d980dc77f3d9d2e5e54c667298a9c2a918f9654c/R/stochastic_binomial_vitalDynamic.R#L30-L32

**Comment by ashokkrish** [comment]
@kle6951 Can you please handle this issue asap please?

**Comment by kle6951** [comment]
Hi Ashok, I am currently out of town with my family this weekend. I will
look at this issue asap when I get home this evening.
