### ISSUE TITLE
Integrate Plotly's react-chart-editor for editing Plotly charts

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#125]
~~1. Follow the guide from Plotly themselves to integrate Plotly Chart Studio in your own development version (your clone); this will inform you on the process the end user needs to follow to use it as well.~~
~~2. Write documentation, appearing in a `shinyhelper::helper()` modal to edit their Plotly chart.~~
~~3. Include a button in the Plotly modebar which will trigger said helper the first time it is pressed (if and only if no Plotly Chart Studio API key is not found on the user's system), and otherwise send the plot data to Plotly Chart Studio and open the website so that user's can edit their chart for publication purposes.~~
- [x] Integrate the [react-chart-editor](https://github.com/plotly/react-chart-editor)

See the short chat we had on Discord for more information; I posted several links in that discussion.

**Comment by Toby-exe** [comment]
I can do this as well but would it not be nicer to use the react-chart-editor ? If most users will be accessing this app via Ashok's deployment they could customize the plot without having to leave the app. I have already started work on this by adding a btn to the modeBar to the plotly plot that opens a popup (similar to the popup the comes from helper() but larger) and my plan was to add the chart-editor component here using the shiny react package. I could instead implement this workflow first (Chart Studio) and the in app chart editor later.

**Comment by bryce-carson** [comment]
> I can do this as well but would it not be nicer to use the react-chart-editor?

The react-based chart editor would be nicer. I think Ashok's target users would have some difficulty setting up an API key, and instructing users to follow a process is a notorious technical writing challenge.

If you see a clear path forward for integrating the react-based chart editor _in the application_, do that.

> If most users will be accessing this app via Ashok's deployment

Ashok has said that he's only using shinyapps.io (and other things like GCP or Oracle Cloud) to just test the application on another machine. The target user will download the application and run it locally.

> If most users will be accessing this app via Ashok's deployment, they could customize the plot without having to leave the app.

Whether the application is running locally or via a deployment isn't the matter, but indeed: plot customization _without leaving Episim is ideal._

> I have already started work on this by adding a btn to the modeBar to the plotly plot that opens a popup (similar to the popup the comes from helper() but larger),

Excellent! Can you attach a screenshot? What icon are you using? I suggest something like a pencil ✏️ from the _bsicons_ package.

> my plan was to add the chart-editor component here using the shiny react package.

Great!

> I could instead implement this workflow first (Chart Studio) and the in app chart editor later.

I created this issue to track development progress on chart editing using the official---and much more featureful---plot editor. I only suggest Chart Studio here (as I did in the initial Discord discussion) because I think it will be _quicker and easier_ to implement, but considering the target audience it might be better to keep it local and in-app even though the upfront development effort is higher. You spent nearly three weeks on an ad-hoc solution anyways, so the development cost shouldn't be an issue. I was thinking of the pace of development, given we want to shift developer effort to spatialEpisim entirely quite soon.

**Comment by bryce-carson** [comment]
> I could instead implement this workflow first (Chart Studio) and the in app chart editor later.

Just integrate the in-app, react-based editor. It's a choice between these two offerings (cloud or local); I merely thought the cloud choice would be quicker and easier, but with the API key stuff and instructing users on how to set that up the in-app choice is definitely better.
