### ISSUE TITLE
Error on initial load

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#132]
@bryce-carson @kle6951 @Toby-exe 

```
Warning: Error in renderUI: object 'epi' not found
  99: select
  97: renderUI [C:\Users\ashok\Desktop\spatialEpisim2022\episim-2.0-beta/server.R#261]
  96: func
  83: renderFunc
  82: output$outputPanel
   1: shiny::runApp
```

<img width="194" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/219fcc7b-75e3-4065-a09e-40f4bb053489">

**Comment by bryce-carson** [comment]
Please reinstall the ehpi package. In a prior version I forgot to export the symbol; it is now exported, and I call the symbol as `epi`, rather than `ehpi::epi` or `ehpi:::epi` as before. That will resolve this issue for you.

**Comment by ashokkrish** [comment]
Remind me what is code to install the ehpi package on a RStudio console?

**Comment by bryce-carson** [comment]
> Remind me what is code to install the ehpi package on a RStudio console?

It is the following (it is also in global.R, because the code is used to install the package if not already installed; like other packages, updates are manual).

Interactively, without any checks that it is already installed, the code is:

```R
library(devtools)
install_github("bryce-carson/ehpi")
```
