### ISSUE TITLE
Toggling from PMA to TMA

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#135]
@bryce-carson @kle6951 @Toby-exe 

**Toggling from PMA to TMA results in a plot as follows**

<img width="788" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/0eb6ffd5-0c3f-46e2-b3fd-2ad9490c7b1d">

In my earlier requests I had outlined the specific defaults I want for a PMA Deterministic SIR and TMA Deterministic SIR. Please follow those instructions so the plot renders properly.

**Comment by bryce-carson** [comment]
I'm surpised if the parameters aren't correct. I'll check,

**Comment by bryce-carson** [comment]
@ashokkrish, I'm quite sure that the values of `defaults()` is still correct. I had renamed the "freezeNumericInputValues` input to just `freeze` and when I did that the implied directionality of the booleans needed to change, but I forgot one.

I fixed that, and now when I change to TMA the graph looks quite nice and similar to the PMA one.
