### ISSUE TITLE
BUG: x-axis is not adjusting to the Number of Timesteps (m) value

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#136]
Please treat this as an urgent request @bryce-carson @Toby-exe @kle6951 

If the user enters the Number of Timesteps (m) as 50 the plot should be

<img width="631" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/52379450-1b74-451f-ade7-a1fab7b13b42">

If the user enters the Number of Timesteps (m) as 500 the plot should be

<img width="632" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/ac433395-5c56-43d1-afe8-189497fb66c3">

But the **current implementation is not behaving this way at all**. It remains as follows

<img width="678" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/6d5a5ccf-9ebb-42b9-8d3c-4614191c457c">

no matter that the user enter for the Number of Timesteps (m)

**Comment by bryce-carson** [comment]
Oh my... thank you for noticing that!

**Comment by bryce-carson** [comment]
@ashokkrish, fixed in [ehpi 0.7.0](https://github.com/bryce-carson/ehpi/commit/d72c9a0d70bb79c1ed3f4eab0d59e2b140b59702). See the commit message details for an explanation.
