### ISSUE TITLE
BUG: Changing vital dynamics does nothing to model or plots

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#137]
@kle6951 @Toby-exe @bryce-carson 

If I change the 

<img width="112" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/dadc35e3-bdb1-41f1-9b22-2fe39005c7f5">

and 

<img width="206" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/a94d39f7-a9c2-4219-9c45-2e9449dfe22d">

I don't see any changes happening to the plots on the mainPanel. This is a bug. Can one of you fix this asap?

**Comment by kle6951** [comment]
Dear Ashok, does it happen to which model option? Since I just tested the binomial with vital dynamic values, the plot is rendered correctly with muB and muD set to 0.01

**Comment by ashokkrish** [comment]
@kle6951 I am trying for the **Deterministic models** and there is no effect of the vital dynamics. As I change the values for mu_D and mu_D nothing happens to the plots Clearly this is a bug that needs to be addressed.

**Comment by bryce-carson** [comment]
@ashokkrish I have fixed the issue. You need to update ehpi to 0.8.0. The formal arguments, muB and muD, were misnamed. I have renamed them to align to the names of the arguments passed to the function by Shiny, which were muBirth and muDeath.

Vital Dynamics now works. Guaranted.
