### ISSUE TITLE
Warning/Error on the RStudio console

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#138]
@bryce-carson When I switch from a Deterministic to a Stochastic model I get this Warning/Error on the RStudio console.

```
Warning: Error in <Anonymous>: argument "replicates" is missing, with no default
  101: <Anonymous> [C:\Users\ashok\Desktop\spatialEpisim2022\episim\R\stochastic_binom.R#13]
   97: renderUI [C:\Users\ashok\Desktop\spatialEpisim2022\episim/server.R#261]
   96: func
   83: renderFunc
   82: output$outputPanel
    1: shiny::runApp
```

Can you fix this please?

**Comment by bryce-carson** [comment]
> Can you fix this please?

No.

**Comment by bryce-carson** [comment]
@ashokkrish, see this thread. #143 is a duplicate of this issue, which is a duplicate of #98.

There are already protections in the application to prevent the appearance of the error, but they don't seem to be effective enough. I will try to harden them.
