### ISSUE TITLE
Default values for the deterministic SEIR model under TMA 

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#139]
@kle6951 

I would the following to be the default values for the **deterministic SEIR model under TMA** 

<img width="231" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/a68f37cb-57b5-4a42-bcbf-f14511cfe2a8">

<img width="235" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/3fa65f52-1800-496d-8dcd-da8b7d9f57cc">

One of you kindly hardcode this asap.

**Comment by ashokkrish** [comment]
@kle6951 

For the SEIR model under TMA I want the number of timesteps in this case to be 500 please

<img width="236" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/3ac077eb-5898-46dd-976c-164f205a6042">

It is defaulting to 40 for some reason. Please make this change to the default values.

Please note for the SEIR model under PMA I want the number of timesteps to remain as 40.

**Comment by bryce-carson** [comment]
@ashokkrish Hi Ashok,

The data/defaultInputValues.xls file is such that you should have no trouble updating it yourself when you want a specific change. Turn-around will be faster if you manage this file's contents henceforth.

**Comment by ashokkrish** [comment]
> The data/defaultInputValues.xls file is such that you should have no trouble updating it yourself when you want a specific change. Turn-around will be faster if you manage this file's contents henceforth.

Sounds good @bryce-carson I will update and push the latest .xls file.
