### ISSUE TITLE
Initial toggle from Deterministic to Stochastic displays an error, then it disappers

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#143]
<img width="323" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/1fa3528e-5b9e-4816-9887-fcfd70356beb">

With the following message on the console

```
Warning: Error in <Anonymous>: argument "replicates" is missing, with no default
  101: <Anonymous> [C:\Users\ashok\Desktop\spatialEpisim2022\episim\R\stochastic_binom.R#13]
   97: renderUI [C:\Users\ashok\Desktop\spatialEpisim2022\episim/server.R#278]
   96: func
   83: renderFunc
   82: output$outputPanel
    1: shiny::runApp
```

After a small time delay the stochastic plots appear on the mainPanel(). Is there a way to prevent from this error to appear to begin with?

**Comment by bryce-carson** [comment]
Hi @ashokkrish, please [see this comment](https://github.com/ashokkrish/episim/issues/138#issuecomment-2197432862).

I am unsure of a way to prevent the error from appearing initially, but I will investigate this later next week because it is low priority.
