### ISSUE TITLE
SIRS

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#17]
- Implement the SIRS model
- Write the necessary LaTeX generating function in R/model_LaTeX.R: https://github.com/ashokkrish/episim/blob/main/R/model_LaTeX.R#L24-L29

**Comment by ashokkrish** [comment]
You are right the symbol should be xi not ksi.

**Comment by kle6951** [comment]
Just a quick update on my progress, I am currently reviewing the ui.R, server.R and changes made by Tobias (ie: stylish code). However, I'm also waiting for Jordan to schedule a meeting to get my git fixed.

**Comment by bryce-carson** [comment]
Thanks, Khanh.

It sucks Git is being such a pain! Maybe you can manually copy and paste your changes into an online editor. GitHub online editor is actuslly VS Code, which you're more comfortable in, you said.

:)

You might be able to push changes or make PRs that way until your local Git installation is fixed.
