### ISSUE TITLE
Remove the left-hand labels and left-indent equations in the mathematical models

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#33]
I would like the ODEs rendered without this left border text

<img width="101" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/ad909c1b-c14c-45c2-bbfa-8d8488ddc1cf">

Let's **left indent all the equations**. 

For example, an SIR model without vital dynamics under the pseudo mass action formulation would look like this

<img width="139" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/8dc0f2a7-9bb3-4508-be4d-6091a3a6a92d">

Another example, an SEIRD model under the true mass action formulation would like this

<img width="179" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/10b39f08-7182-429c-b5b4-c81f83ae12f2">

_Originally posted by @ashokkrish in https://github.com/ashokkrish/episim/issues/31#issuecomment-2106118570_

**Comment by bryce-carson** [comment]
@kle6951, once we are done with your outstanding pull request, you can start to work on this _if you'd like_.

**Comment by kle6951** [comment]
Yeah sure
