### ISSUE TITLE
Refactor the code-base to refer to massActionSelect, rather than `qValue`

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#34]
The UI code below shows how the model formulation (mass action type) is currently described. We describe it as the "formulation of the model"; that might not be apt. Regardless of wording, the radio button determines whether the model uses true mass action or pseudo mass action.

https://github.com/ashokkrish/episim/blob/0b08cd7d86eac26db7ff2b7e2913743dc434598c/ui.R#L10-L15

In other areas of the codebase, wherever `qValue` is referred to it must be changed to something more appropriate and meaningful: `massActionSelect`. This would then be accessed as `input$massActionSelect` rather than `input$qValue`.

Subsequent $\LaTeX{}$ changes in the mathematical model tab will take advantage of this change and the code should be more readable.

**Comment by Toby-exe** [comment]
I have assigned this to myself, if the intention was not for one of us to pick this up let me know

**Comment by bryce-carson** [comment]
> I have assigned this to myself, if the intention was not for one of us to pick this up let me know

You can work on it! I hadn't assigned it to anyone because I didn't want to make it a priority. It's okay to work on it if you're not doing anything else, like reading. :) I have a lot of reading to do. 😄
