### ISSUE TITLE
PMA vs TMA formula in LaTeX

### ISSUE THREAD

**Issue by kle6951** [ashokkrish/episim#35]
I would like the ODEs rendered without this left border text

<img width="101" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/ad909c1b-c14c-45c2-bbfa-8d8488ddc1cf">

Let's **left indent all the equations**. 

For example, an SIR model without vital dynamics under the pseudo mass action formulation would look like this

<img width="139" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/8dc0f2a7-9bb3-4508-be4d-6091a3a6a92d">

Another example, an SEIRD model under the true mass action formulation would like this

<img width="179" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/10b39f08-7182-429c-b5b4-c81f83ae12f2">

_Originally posted by @ashokkrish in https://github.com/ashokkrish/episim/issues/31#issuecomment-2106118570_

**Comment by kle6951** [comment]
@ashokkrish In my understanding, models under the TMA formulation will consider the `N` while models under the PMA formula won't consider it.  Please correct my understanding if it's not correct.

**Comment by bryce-carson** [comment]
> @ashokkrish In my understanding, models under the TMA formulation will consider the `N` while models under the PMA formula won't consider it. Please correct my understanding if it's not correct.

That is correct. Partial mass action models have $N^q\text{, where }q = 0$, so division by one occurs (which does nothing).

**Comment by kle6951** [comment]
Sounds good. I will update the equation format in the main panel according to this

**Comment by bryce-carson** [comment]
Your plan to address this issue, which you detailed in your pull request #50 is reasonable.

Don't make any changes to server.R, however. I will ensure that the $\LaTeX{}$ functions are called with the values they need as soon as I finish the refactoring I'm doing in server now (it's almost done).

You'll need qValue, but I think we renamed it to massActionSelect. You can expect that when the functions you're writing are called (you're calling them inside the other latex functions) that the value of `massActionSelect` will be passed. You can modify the latex functions to accept this value as necessary, please.

**Comment by bryce-carson** [comment]
> Sounds good. I will update the equation format in the main panel according to this

Indeed, you can simply remove the fraction, so $\frac{\beta{}SI}{N}$ becomes just $\beta{}SI$.

**Comment by kle6951** [comment]
I will leave the code in the `server.r` untouched. My plan is to add only extra parameters to the latex functions of each model (ie: qValue). As you said, as I will call functions inside the latex function, I need to modify the latex function.
