### ISSUE TITLE
Choose a package to make easy diagrams to replace the images in www/

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#38]
It would be nice to use a JavaScript library wrapped up in an R package to make diagrams programmatically. The images in www/ don't cover all the models we might implement.

**Comment by ashokkrish** [comment]
I agree, we need dynamic flowcharts. If anyone has the expertise you can self assign this task. There are other tools out these to generate flowcharts but with and without vital dynamics would have us create way too many flowcharts instead a dynamic one is preferred.

**Comment by bryce-carson** [comment]
We are using **mermaid.live**.
