### ISSUE TITLE
Populate Basic Reproduction Number (R₀) tabPanel with content

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#40]
The basic reproduction number or basic reproduction ratio (denoted **R0**) represents the average number of secondary  infections  produced  from  a  single  infected  individual  introduced into a completely susceptible population.

For each deterministic compartmental models we need to first come up with the next-generation matrix (NGM) for the system at disease free equilibrium, denoted _K_. The entries of matrix _K_ are all positive. The largest (or dominant) eigenvalue of the NGM is **R0**. We also should establish that the sum of the eigenvalues of _K_ is equal to the trace of _K_. For stochastic models it is known as the
“mean offspring matrix”.

<img width="151" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/01d193a9-2a84-49ac-acf9-65a54ab36b08">

where the _F_ and _V_ are matrices. The entries of matrix _F_ relate to the number of new infections caused by an infective entering the population. Matrix _F_ has rank 1. _ρ_ denotes the spectral radius.

Add a dedicated tabPanel() where we will first derive the R0 formula and then go on to calculate the value based on user input. Details are as follows. 

```diff
+ this text is highlighted in green
- this text is highlighted in red -
! this text is highlighted in orange !
@@ this text is highlighted in pink @@
# this text is highlighted in grey  #
```

**Comment by bryce-carson** [comment]
@ashokkrish, and @kle6951,

Now that the tabPanel has been added I have updated this issue to reflect what is now desired (populating it with content). Thanks for the merge, @kle6951.
