### ISSUE TITLE
Assumption of constant population is not valid for models with vital dynamics

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#41]
For models with a closed population we check if _N_ equals the sum of all the values in all the compartments (except D). Here _N_ is a constant. Please note that this assumption of constant population is not valid for models with vital dynamics.

**Comment by bryce-carson** [comment]
@ashokkrish, what needs to change in the implementation for this? The model equations in all the R/*_solve.R files recalculate N.
https://github.com/ashokkrish/episim/blob/f51ca44995343bd9f71457af78f7d072b47097b3/R/SIRD_solve.R#L1-L14
Should we make an assertion in models where the simplifying assumption that $N$ is constant to verify that it is? When the assertion is violated at any point, or by some margin of error, we can issue a warning.

**Comment by ashokkrish** [comment]
_N_ is the total persons living at any time. For a model without the _D_ compartment and no vital dynamics this _N_ will always default to the total population. 

But when a model is developed with the _D_ compartment we need to be extra careful as the contacts of _I_ happens only with all persons living at that time.

**Comment by bryce-carson** [comment]
Okay, the two models with $D$ compartments are presently correct, in that case.

https://github.com/ashokkrish/episim/blob/f51ca44995343bd9f71457af78f7d072b47097b3/R/SEIRD_solve.R#L14

https://github.com/ashokkrish/episim/blob/f51ca44995343bd9f71457af78f7d072b47097b3/R/SIRD_solve.R#L12

**Comment by bryce-carson** [comment]
In models without $D$ compartments should we positively use a constant $N$, _not recalculating it_?

**Comment by ashokkrish** [comment]
> Will change to
> 
> ```r
>  list(c(dS, dE, dI, dR, N), q)
> ```

I need to think about this. Will do this by hand and get back to you.

**Comment by ashokkrish** [comment]
> Will change to
> 
> ```r
>  list(c(dS, dE, dI, dR, N), q)
> ```

I see that _dN_ in models with the _D_ compartment is correctly calculated so the above change may not be correct.

**Comment by ashokkrish** [comment]
Indeed _N_ is recalculated for models with the _D_ compartment.

**Comment by bryce-carson** [comment]
> > Will change to
> > ```r
> >  list(c(dS, dE, dI, dR, N), q)
> > ```
> 
> I see that _dN_ in models with the _D_ compartment is correctly calculated so the above change may not be correct.

Yes, I misread the value of the vector. The lowercase ds confused me when I read it. There is no change necessary. 😄
