### ISSUE TITLE
Model plots faceted on compartment

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#43]
@ashokkrish wants additional plots, faceted on the model compartments (à la SVEIRDS).

> Please note that we want plots for all compartments in a single plot as well as separate plots of individual compartments.
> 
> Plots for individual compartments have a custom header and x-axis label.
> 
> We can either plot all of them to begin with or let the user select which plots they’d like displayed.

- [x] Plots faceted on compartment, with axis labelling
- [ ] Choice between viewing compartments individually or in a combined plot

**Comment by Toby-exe** [comment]
![image](https://github.com/ashokkrish/episim/assets/104709648/b3c35d08-7fdf-43d8-8e72-2149f0bfe2f0)
This is the current state of the subplots I have created using facet_wrap. Am I headed in the right direction ? For reference run I have the scale in facet_wrap set to free so that each subplot has its own x axis and y axis labels (values) 

Optionally we can also you facet_grid()
![image](https://github.com/ashokkrish/episim/assets/104709648/822f2b8b-4b72-4bab-9651-d94fe555bbd7)

But I think facet_wrap is the better of the two in this case

**Comment by Toby-exe** [comment]
initially I had set 'scale' to "free_y" but this removes time labeling on the x-axis for subplot above other subplots: 
![image](https://github.com/ashokkrish/episim/assets/104709648/6360ead2-4d0d-403a-b790-df7db74f35de)
This does not look bad or anything but it does mean if a subplot is above another only the bottom one will have the time intervals labelled

**Comment by bryce-carson** [comment]
Interesting. Read the function documentation again and see what the cause of that is. Having the x-axis plotted for the compartments drawn above other compartments is not so important, because the figure below "shares" the same x-axis and the figures are aligned nicely. 

The most important thing is that the y-axis has the same scaling and labelling.

**Comment by Toby-exe** [comment]
Sorry I misread your comment, but even so the same apply for the y axis:

![image](https://github.com/ashokkrish/episim/assets/104709648/59e9cd79-bf61-409b-b1aa-d492b7b63857)

Still looks great, but if you wanted every plot to have its own interval labels lmk and I will find a way to do that

**Comment by Toby-exe** [comment]
> Sorry I misread your comment, but even so the same applies for the y axis:
> 
> ![image](https://private-user-images.githubusercontent.com/104709648/331381389-59e9cd79-bf61-409b-b1aa-d492b7b63857.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTMzNDgsIm5iZiI6MTcxNTg5MzA0OCwicGF0aCI6Ii8xMDQ3MDk2NDgvMzMxMzgxMzg5LTU5ZTljZDc5LWJmNjEtNDA5Yi1iMWFhLWQ0OTJiN2I2Mzg1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMDU3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjgxZTU2NTMxZTNiMzExMWFjMWE5ZTJhNGY1YzdiN2QxMzYwOTU2NjhkN2JhOWFhNDUwZDc4OTBkODNlZTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.skqnPcKseOlucg5Vd1pIDFAkJtHMGNfJjUqWImyGIK0)
> 
> Still looks great, but if you wanted every plot to have its own interval labels lmk and I will find a way to do that

This is with scale set to "fixed" so they all have the same x and y axis scale

**Comment by bryce-carson** [comment]
Looks fine to me! Thanks.

**Comment by Toby-exe** [comment]
Note: from meeting on Friday, make each subplot its own (with it's own x and y)

**Comment by bryce-carson** [comment]
It would be nice if you could change the vertical axis label to the name of the compartment, e.g. 'Susceptible', rather than "Number of people." In the main plot, I think a vertical axis label of "People" is sufficient, given the axis is numerical anyway. Please refer to the screenshots.

As for the title of the plots, I'm unsure if there is a better description. @ashokkrish, can you please provide your input on the plot titling?

### Screenshots
![newplot(1)](https://github.com/ashokkrish/episim/assets/51974245/94a79218-28f9-4641-88c1-3ed47c476e99)
![newplot(2)](https://github.com/ashokkrish/episim/assets/51974245/c5d8da75-765b-495e-bc17-cc477f0e0bca)
![newplot(3)](https://github.com/ashokkrish/episim/assets/51974245/0f7702bd-aa1f-49a6-82aa-255a96a89521)

**Comment by Toby-exe** [comment]
Implemented the y axis change 10e6d5ff8adb0b84dd679a430dd40794f53f18f7. Will wait for @ashokkrish feedback for what we should do with the titles 

> It would be nice if you could change the vertical axis label to the name of the compartment, e.g. 'Susceptible', rather than "Number of people." In the main plot, I think a vertical axis label of "People" is sufficient, given the axis is numerical anyway. Please refer to the screenshots.
> 
> As for the title of the plots, I'm unsure if there is a better description. @ashokkrish, can you please provide your input on the plot titling?
> 
> ### Screenshots
> ![newplot(1)](https://private-user-images.githubusercontent.com/51974245/334592462-94a79218-28f9-4641-88c1-3ed47c476e99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MzY5MjUsIm5iZiI6MTcxNjkzNjYyNSwicGF0aCI6Ii81MTk3NDI0NS8zMzQ1OTI0NjItOTRhNzkyMTgtMjhmOS00NjQxLTg4YzEtM2VkNDdjNDc2ZTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDIyNTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MDA4N2IzZDFmN2ZlNjdlZjhlZGZhNzMzZGQ3YzI1YzFhNzczMGM3YmQ0ZmY5Nzc0Y2JhNDE1NWZhODllNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tjbA_I4JHOZn6hodtyIam5DRIbJDSwtaNsQG6_fBlcM) ![newplot(2)](https://private-user-images.githubusercontent.com/51974245/334592467-c5d8da75-765b-495e-bc17-cc477f0e0bca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MzY5MjUsIm5iZiI6MTcxNjkzNjYyNSwicGF0aCI6Ii81MTk3NDI0NS8zMzQ1OTI0NjctYzVkOGRhNzUtNzY1Yi00OTVlLWJjMTctY2M0NzdmMGUwYmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDIyNTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOTRmYjYyYzJhOThiNmE4YmJiOTkwZDEyNDUzMTA4NjQyZjAxYjc2ODE4ZDIwZTcxZjI0YjI3ZjkyOTNlZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ddlYbT4mbZoiDQab421hmAkK93dQ4ClHDiabiz7T2U) ![newplot(3)](https://private-user-images.githubusercontent.com/51974245/334592819-0f7702bd-aa1f-49a6-82aa-255a96a89521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MzY5MjUsIm5iZiI6MTcxNjkzNjYyNSwicGF0aCI6Ii81MTk3NDI0NS8zMzQ1OTI4MTktMGY3NzAyYmQtYWExZi00OWE2LTgyYWEtMjU1YTk2YTg5NTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDIyNTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMmNjOGQ2MGNmN2ViMWY1MTk3OTM5YWE1MDI2YzYxNWVjYzNkNzdjZWZkMTAwOWI5ZWVkZTJiNDFlYmYyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M4GydF9DT2RmTT05iV_kMHNSMpYfVs9adYvDcoEc68U)

**Comment by Toby-exe** [comment]
Completed in 107fb56325a5b514058b1f261a82df60330721c0
