### ISSUE TITLE
User experience; model workflow/wizard

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#48]
Each of the six non-spatial epidemic models (SIR, SIRD, SIRS, SEIR, SEIRD, SEIRS) can run
- [x] in a deterministic versus stochastic fashion.
  - Radio Button
  - toggling this should clear the mainPanel
- [x] with or without vital dynamics.
  - Checkbox
  - toggling this should clear the mainPanel
- [x] in a true mass action versus (TMA) or pseudo mass action (PMA) formulation.
  - Radio Button
  - toggling this should clear the mainPanel

**Comment by bryce-carson** [comment]
The deterministic/stochastic is unchecked because the toggle is non-functional (nothing changes). When stochastic models are implemented this will be fulfilled.

**Comment by ashokkrish** [comment]
Can we default the deterministic be selected though?

**Comment by bryce-carson** [comment]
> Can we default the deterministic be selected though?

Yes, I meant only here in the task list. In the application the default selection will be deterministic.
