### ISSUE TITLE
Update 𝒅𝒆𝒇𝒂𝒖𝒍𝒕𝑰𝒏𝒑𝒖𝒕𝑽𝒂𝒍𝒖𝒆𝒔.𝒙𝒍𝒔𝒙 spreadsheet with literature-based epidemic model parameters and variables

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#49]
1. Download the [Spreadsheet on Google Sheets [restricted access]](https://docs.google.com/spreadsheets/d/1HQDvEo4En7I9_5odgREmoooleqnPxlSmd97kh9GDSh8/edit#gid=1876689347)
2. Add it to the repository
3. Update the binary (the spreadsheet) periodically and ensure the `read.xlsx` function call is updated as necessary if columns change or need to be read with different names than in the spreadsheet

**Comment by ashokkrish** [comment]
The spreadsheet is not even close to be ready. There are a lot of gaps and not enough actual test cases. For now we could directly access the spreadsheet from the drive rather than save it locally. Your thoughts?

**Comment by bryce-carson** [comment]
I believe accessing the data from the spreadsheet (regardless of completion) locally, and distributing it with the application, is going to be easier to maintain (for now) than accessing the same data through the Google Sheets API.

It's easier to deal with Excel files than it is to deal with web APIs, and we won't need to worry about any security concerns because there will be an "air gap" (no connection between the two things).

For now, this issue just exists to document that this is a thing I think we should do in the future. We don't need to resovle it immediately. It's long-term, more towards the end of the month of May.

**Comment by bryce-carson** [comment]
@kle6951, I assigned you to this task because you told me Ashok asked you to add some values to the spreadsheet.

Let me know how I can help you complete this task sooner so I can work on the dependent task (literature model select).

**Comment by kle6951** [comment]
I pushed the change to the data spreadsheet to the main branch. Let me know if you do anything else for the spreadsheet 😁

**Comment by kle6951** [comment]
I'm going to reformat the header/title for the model-literature-based model on Google Spreadsheet to ensure the format is consistent with the default spreadsheet.
