### ISSUE TITLE
Fix the LaTeX rendering issue for the model parameter widgets

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#5]
![](https://github.com/ashokkrish/episim/assets/51974245/972cb6b8-1e34-40ec-a90f-9da97994a904)

It probably only requires wrapping the function call that constructs these widgerts in a call to `withMathJax`.

*   There's a more elegant solution, likely; I'll make another issue for discussion of how to handle MathJax in the application.
*   Don't worry about the validation error message below the input field. That's a separate issue.

**Comment by ashokkrish** [comment]
Are we using mathJax here? In spatialEpisim I think the Greek alphabets render without issues.

**Comment by bryce-carson** [comment]
> Are we using mathJax here?

Yes, [MathJax is the JavaScript library](https://www.mathjax.org/) we're using to render $\LaTeX{}$.
