### ISSUE TITLE
DataTable appearance options or configuration should be like the usage in Statnet's *epidcm* Shiny app

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#56]
Currently we are printing

<img width="350" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/e00edbfd-1de3-4ada-9db4-079da934fb35">

See this R Shiny app (https://statnet.shinyapps.io/epidcm/) specifically their third tabPanel called **Data**.  I want our Output Summary to rendered this way as well. Have the option to sort ascending/descending on any column. I also would like the user to be able to download the Output Summary as an Excel file like they do.

If you look at the regression and correlation output from CougarStats (https://www.cougarstats.ca/) the data table is printed as follows

<img width="576" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/f44cb63d-fc16-4eaf-8f78-20f776b45588">

You are able to select any rows as needed.

**Comment by bryce-carson** [comment]
@Toby-exe, this is a duplicate/related to #52. See Ashok's requests in this thread.

**Comment by bryce-carson** [comment]
The issue has disappeared, and the table looks like what Ashok screen-shotted, so I'm going to close this issue-tracker for now.
