### ISSUE TITLE
Authors tab needs grammatical fix

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#57]
> Khanh Le, Tobias Wondwossen
>
> Developer - Undergraduate Student, Mount Royal University, Calgary, AB, CANADA

This should be two listings, one for each contributor. Anticipating a far future where there are many authors and having a single attribution line for people in the same role/institution is not appropriate at this point.

In the future wherein that does happen, authors of a similar or the same role should be listed on the same line, with superscripts used to link to footnotes listing the institutions and companies with which each author is affiliated.

**Comment by ashokkrish** [comment]
We will be merging it with the spatialEpisim authors tab so don't worry about it too much for now.
