### ISSUE TITLE
When the Shiny app first runs do not show the four tabPanels

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#6]
When I press Run App on RStudio the four tabPanels in the mainPanel appears and after several seconds they disappear. See if the tabPanels only appear when the user clicks the Run Simulation button.

**Comment by bryce-carson** [comment]
@ashokkrish, what do you think about displaying cached results when changing to a _deterministic_ model you have previously looked at (if and only if the model configuration, variables, and parameters have not changed at all)?

For example, if I configure an SIR model and then run the simulation the output panel (with the four tabs in the tabPanel) will then be revealed. If I then change to a different model, I can be expected to need to configure it if I have not run it before; however, if I have run that model before then the last used configuration should be restored (if and only if it was a configuration for a deterministic simulation).

It might take a lot to implement that, however, so it's a long-term idea that we probably won't implement.

Regardless of this proposed idea, I have fixed this issue and it will be resolved with an incoming commit.

**Comment by ashokkrish** [comment]
@bryce-carson I will follow your advice on this. Although I feel like caching is probably too high of a priority right now. We can clear the mainPanel() each time the user switches to a new model.
