### ISSUE TITLE
Write more appropriate and helpful input validation error messages for model parameter widgets

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#7]
![](https://github.com/ashokkrish/episim/assets/51974245/3e46e0aa-915d-4516-9ad2-dc02b11ef8f5)

"Must not contain `NA` values." is horribly insufficient for what the actual issue is.

*   When the required value is numeric, tell the user that the input must be a number.
*   When the number is out of range, informing the user of the range that is acceptable is implemented in shinyValidate already.
*   Play with the widgets and find out which ones display the pictured message, and think of and implement appropriate replacements.

**Comment by ashokkrish** [comment]
When the field is blank a Required warning to appear on the bottom.

**Comment by ashokkrish** [comment]
<img width="235" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/2827f41e-9a63-4a2d-8a3c-6926c9d661ee">

**Comment by bryce-carson** [comment]
> @bryce-carson  I have pushed the code

Okay. Did you address this issue specifically? It is for tracking the actual error messages that are displayed, not whether they are properly displayed or not as we were having you fix.

**Comment by kle6951** [comment]
Oh yeah, I misunderstood the issue. I will remove the issue from my pull request. I apologize for it

**Comment by bryce-carson** [comment]
> Oh yeah, I misunderstood the issue. I will remove the issue from my pull request. I apologize for it

It's okay. I updated the description of the PR and merged it.

**Comment by kle6951** [comment]
> > Oh yeah, I misunderstood the issue. I will remove the issue from my pull request. I apologize for it
> 
> It's okay. I updated the description of the PR and merged it.

Thank you for doing that!

**Comment by bryce-carson** [comment]
@kle6951, https://github.com/ashokkrish/episim/commit/f57221972021bb8e2d5815eeaf98a8416ca13a46 may have resolved this issue. What do you think? Can you tell me what better message we can use for shiny validate rules other than required? The required rule, now that it is applied first, will say, "Required," when the widget doesn't have any value. What about when a negative number is input in a numeric widget requiring positive numbers? Is the default message sufficient? If so, please close this issue after you review the defaults.

**Comment by kle6951** [comment]
I'll take a look at the latest code and the message. I'll update it if necessary.

**Comment by kle6951** [comment]
All messages are good.

**Comment by kle6951** [comment]
All messages are good

**Comment by bryce-carson** [comment]
> All messages are good 

Thanks!
