### ISSUE TITLE
Deploying the app to ShinyApps.io

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#75]
Each time I try to publish the current code as a Shiny app to the [ShinyApps.io server](https://www.shinyapps.io/) it crashes. Could one of you take a look at this please?

**Comment by bryce-carson** [comment]
I will look at this soon. I want to delay it until we have a working application before I bother, because other errors have priority; there's no point in pushing broken code, right?

**Comment by bryce-carson** [comment]
@ashokkrish Does it all work nicely?

**Comment by ashokkrish** [comment]
@bryce-carson I am able to deploy the episim project from within RStudio without issues. You can see the deployed version here: https://spatialepisim.shinyapps.io/episim/
