### ISSUE TITLE
Main output plot time scale is too long by default

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#79]
With fifty timesteps in an SIR model, the x-axis should be no more than fifty-five, so that the plot is not downscaled horizontally at first. The user can always scale the plot down afterwards if needed, but the x-axis should be about the same as what there is for data.
![newplot](https://github.com/ashokkrish/episim/assets/51974245/5d3ca1a1-032a-438b-be98-918d71bef931)

**Comment by Toby-exe** [comment]
this is an easy fix, but I wont know if my fix is working since the plots all go to 99 (in time) regardless of the time steps entered in the options. As soon as the plotting is fixed I will make sure the x scale is aligned with the number of time steps

**Comment by bryce-carson** [comment]
> this is an easy fix, but I wont know if my fix is working since the plots all go to 99 (in time) regardless of the time steps entered in the options. As soon as the plotting is fixed I will make sure the x scale is aligned with the number of time steps

Okay, which issue is blocking this? I thought the rest of plotting was already fixed by your recent commit. Are there new errors, or were you waiting for my changes to the model solvers to see if your latest changes resolved plotting issues?

**Comment by Toby-exe** [comment]
sorry I made this commit before I saw that you had fixed the other issues in your most recent commit. Everything is working for me as of your most recent commit, so I will push the fix for the scale shortly

**Comment by Toby-exe** [comment]
There seems to be some other weird behaviour now. Previously (before you most recent commit) the data table and plot use to go to 99 and the numbers were growing like crazy. Now there is only values for the "time" up to 50 (which is better) but it still seems to be plotting to 99. This is probably a horrible explanation so if you have time for a quick call I can show you what I mean.

**Comment by bryce-carson** [comment]
> There seems to be some other weird behaviour now. Previously (before you most recent commit) the data table and plot use to go to 99 and the numbers were growing like crazy. Now there is only values for the "time" up to 50 (which is better) but it still seems to be plotting to 99. This is probably a horrible explanation so if you have time for a quick call I can show you what I mean.

I apologize. I was working on the 1.0.0-devel release and not watching my email or phone for notifications, so you couldn't contact me and ask to meet virtually otherwise.

Could you provide some screenshots instead? I'm not sure what you mean by there "only [being] values for the "time" up to 50," being different than before. I didn't change anything related to plotting in my commits.

**Comment by Toby-exe** [comment]
![image](https://github.com/ashokkrish/episim/assets/104709648/8ecfaf1c-c30d-4074-81ec-4ab662418dc0)

My understanding is that if we are running the model for 50 time steps then the table should only be 50 rows long. But it seems no matter what value is entered for "time step" the data table for any model after its run is 99. This is a problem for #79 (this issue) because if I set the scale of the x axis to what ever the "max time" was in the modelResults it will always be 99

here is the rest of the same table from above:

![image](https://github.com/ashokkrish/episim/assets/104709648/e9b8819d-5708-492f-b9e1-a2984e7c4023)

**Comment by bryce-carson** [comment]
> My understanding is that if we are running the model for 50 time steps then the table should only be 50 rows long. But it seems no matter what value is entered for "time step" the data table for any model after its run is 99. This is a problem for #79 (this issue) because if I set the scale of the x axis to what ever the "max time" was in the modelResults it will always be 99

Okay, I understand now. I will see what the solver is doing with timesteps.

The way it should work, if I understand, is the number of rows should be equal to the number of timesteps (say, fifty), and product of the increment (by default one). In the future we should be able to have 48 rows resulting from 4 timesteps with an increment of 1/12 (to represent a simulation of four years with results of the simulation reported once per month).

For now, however, this is definitely wrong and I'll investigate and fix the issue. You can independently resolve the x-axis scale and when the modelling functions are fixed (so that the number of rows in the model is respective to the number of timesteps) it'll make sense. Don't wait.

**Comment by Toby-exe** [comment]
Bryce fixed the data issues in ca598b913f2670dfed8dae77f8665d16827b3d46 which in turn seemed to also resolve this issue. As of now the scale is the same as the amount of "time steps".

**Comment by Toby-exe** [comment]
Bryce fixed the data issues in ca598b913f2670dfed8dae77f8665d16827b3d46 which in turn seemed to also resolve this issue. As of now the scale is the same as the amount of "time steps".
