### ISSUE TITLE
Deprecated function calls in plotting code

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#81]
The following warning is current as of eb90d2db6a996b833f6bbe28414cdc5c1b109719.

> `shiny::renderDataTable()` is deprecated as of shiny 1.8.1.
Please use `DT::renderDT()` instead.
Since you have a suitable version of DT (>= v0.32.1), shiny::renderDataTable() will automatically use DT::renderDT() under-the-hood.
If this happens to break your app, set `options(shiny.legacy.datatable = TRUE)` to get the legacy datatable implementation (or `FALSE` to squelch this message).
See <https://rstudio.github.io/DT/shiny.html> for more information.

If this is outdated, please simply close the issue when you read it, @Toby-exe.

**Comment by Toby-exe** [comment]
reopened since to be in line with changes from 0d18bb305c9c8f806c7914d6aee3209417b3a771 will push fix shortly
