### ISSUE TITLE
`plotSEIRS` not found

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/episim#86]
The latest change, https://github.com/ashokkrish/episim/commit/10e6d5ff8adb0b84dd679a430dd40794f53f18f7, seems to have introduced a regression. The plotting function is not found now.
> Warning: Error in : value for `plotSEIRS` not found
  6: runApp
  5: print.shiny.appobj
  3: ss
  2: .ess.source
  1: base::as.environment("ESSR")$.ess.eval

**Comment by Toby-exe** [comment]
We don't even have a SEIRS_plotte.R lol.

**Comment by Toby-exe** [comment]
I can add one right now. I wonder if we ever even had one to begin with lol.

**Comment by bryce-carson** [comment]
> We don't even have a SEIRS_plotte.R lol.

That would do it! 😆

![](https://user-images.githubusercontent.com/74038190/226127923-0e8b7792-7b3c-462b-951b-63c96ba1a5af.gif)

**Comment by Toby-exe** [comment]
fix in 51be9239bef1c298c937c3709025251ca82a0c46

**Comment by bryce-carson** [comment]
@Toby-exe, wait! I forgot that _SEIR_plotte.R_ _**was** "integrated."_ There used to be an alias such that when plotSEIRS() was needed, it would actually use plotSEIR with a different argument. I took a quick look at _SEIR_plotte.R_, and it appears that your refactoring of the plotting code refactored away that integration/unification. That's okay, because it wasn't documented and it lead to a breakage (this issue!).

You've already fixed it too, so no worries!

Please enjoy this tasteful GIF. Note the presence of the iconic [WRT54GS](https://en.wikipedia.org/wiki/Linksys_WRT54G_series#WRT54GS).
![Runescape2WinXPNostalgia](https://github.com/ashokkrish/episim/assets/51974245/f017d20d-aeb9-4e07-8ef9-e42f24f6fd9b)
