### ISSUE TITLE
Clearing mainPanel()

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#88]
Toggling model formulation should clear the mainPanel()

<img width="284" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/1406c143-124d-4f18-9ec0-6482c565f518">
 
Checking on or off on the Vital Dynamics should clear the mainPanel()

<img width="110" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/7ab209b4-e45f-4c4d-9bf0-edd60a4c1002">

**Comment by bryce-carson** [comment]
@ashokkrish I have fixed this and the issue will be closed in an incoming commit.
