### ISSUE TITLE
Default values on load

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#89]
**For a deterministic SIR model under the Pseudo-Mass Action formulation set the following values as default on load**

- beta = 0.001, gamma = 0.1, N = 500, S = 499, I = 1, R = 0, m = 50. The resulting plot on the mainPanel should look like this,

<img width="805" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/f96e0a50-f5c1-4b5d-a056-a0dcb927a788">
 
**For a deterministic SEIR model under the Pseudo-Mass Action formulation set the following values as default on load**

- beta = 0.08, gamma = 0.10, sigma = 0.05, N = 500, S = 499, E = 0, I = 1, R = 0, m = 40. The resulting plot on the mainPanel should look like this,

<img width="808" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/02c96730-387b-4290-a769-67013c9c7744">
 
Can you verify if these two plots are correctly rendering in our episim project?

**Comment by bryce-carson** [comment]
@ashokkrish, to clarify, you wish the default values to be changed (the ones we load from the spreadsheet in the `defaults` reactive)? Additionally, you want me to verify the appearance of results generated with these defaults?

**Comment by bryce-carson** [comment]
> **For a deterministic SIR model under the Pseudo-Mass Action formulation set the following values as default on load**
> - beta = 0.001,
> - gamma = 0.1,
> - N = 500,
> - S = 499,
> - I = 1,
> - R = 0,
> - m = 50.

Those are already the default parameter values for a deterministic SIR model with pseudo-mass action.

> The resulting plot on the mainPanel should look like this:
> 
> <img alt="image" width="805" src="https://private-user-images.githubusercontent.com/410949/334688055-f96e0a50-f5c1-4b5d-a056-a0dcb927a788.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTUzMDUsIm5iZiI6MTcxNjk5NTAwNSwicGF0aCI6Ii80MTA5NDkvMzM0Njg4MDU1LWY5NmUwYTUwLWY1YzEtNGI1ZC1hMDU2LWEwZGNiOTI3YTc4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxNTAzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmYyMTlkYjg5MjE0MDg1ZTAxMDk4ZDlhNzljZDYyNWQzZGI5ZDA4MGM0MTU5MmU2OGYzODY0NzcwYTI2N2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-BYRk2knjPadmkcxyMCi0Eold0-eMK78P6qmK3ldjUs">

How does this compare?

![newplot(5)](https://github.com/ashokkrish/episim/assets/51974245/b8f3fdf9-15fc-46fa-a662-f008570fc0e8)
[SIR_Model_Summary2024-05-29.xlsx](https://github.com/ashokkrish/episim/files/15486461/SIR_Model_Summary2024-05-29.xlsx)

**Comment by bryce-carson** [comment]
I have noticed a bug with the default values for SIR (at least). That is tracked separately from this in #90 because I'm unsure what the exact issue is you're mentioning here.

**Comment by bryce-carson** [comment]
I have resolved this issue. It will be closed in an incoming commit.

**Comment by ashokkrish** [comment]
For a deterministic SEIR model under the Pseudo-Mass Action formulation can you please set the following values as default on load?

beta = 0.08, gamma = 0.10, sigma = 0.05, N = 500, S = 499, E = 0, I = 1, R = 0, m = 40.

**Comment by ashokkrish** [comment]
For a deterministic SEIR model under the Pseudo-Mass Action formulation can you please set the following values as default on load?

beta = 0.08, gamma = 0.10, sigma = 0.05, N = 500, S = 499, E = 0, I = 1, R = 0, m = 40.

**Comment by bryce-carson** [comment]
> For a deterministic SEIR model under the Pseudo-Mass Action formulation can you please set the following values as default on load?
> 
> beta = 0.08, gamma = 0.10, sigma = 0.05, N = 500, S = 499, E = 0, I = 1, R = 0, m = 40.

If I did not, sure. I'll get to it.

You can always quickly modify the values in the spreadsheet in the data/ folder also. There's no need to request the change (if you have time and the want to do so).

I don't mind making the changes at your request either.

**Comment by bryce-carson** [comment]
> **For a deterministic SIR model under the Pseudo-Mass Action formulation set the following values as default on load**
> 
>     * beta = 0.001, gamma = 0.1, N = 500, S = 499, I = 1, R = 0, m = 50. The resulting plot on the mainPanel should look like this,
> 
> 
> <img alt="image" width="805" src="https://private-user-images.githubusercontent.com/410949/334688055-f96e0a50-f5c1-4b5d-a056-a0dcb927a788.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDIzMjEsIm5iZiI6MTcxNzU0MjAyMSwicGF0aCI6Ii80MTA5NDkvMzM0Njg4MDU1LWY5NmUwYTUwLWY1YzEtNGI1ZC1hMDU2LWEwZGNiOTI3YTc4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQyMzAwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjEwNzI5M2E1M2M4ZmY5MGE0YzBjZmFkNTE4NWU4NTA2ZjU4MzFlMDEzYTNlMzE3OWNlNDYwYTE1NTQzYmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i-gkT88kTxcGpQfm2ODA_olDwIWALlbYxB2YWvl_IyE">
> 
> **For a deterministic SEIR model under the Pseudo-Mass Action formulation set the following values as default on load**
> 
>     * beta = 0.08, gamma = 0.10, sigma = 0.05, N = 500, S = 499, E = 0, I = 1, R = 0, m = 40. The resulting plot on the mainPanel should look like this,
> 
> 
> <img alt="image" width="808" src="https://private-user-images.githubusercontent.com/410949/334690133-02c96730-387b-4290-a769-67013c9c7744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDIzMjEsIm5iZiI6MTcxNzU0MjAyMSwicGF0aCI6Ii80MTA5NDkvMzM0NjkwMTMzLTAyYzk2NzMwLTM4N2ItNDI5MC1hNzY5LTY3MDEzYzljNzc0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQyMzAwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWUwNzNiMjhiNDlkMGFkYTdhNzRkZWNkNzg4YjliZjIzZmMwOGZjMDhiOTdmMjJmZjZkNDk0M2RmMDQxYzIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8Vi_IxrMM0WTQ4flE_Ge4KNdir6OzPh47bSZHz2oTF8">
> 
> Can you verify if these two plots are correctly rendering in our episim project?

In your second request here, beta was off by a magnitude of ten for the plot that you want. I discovered that interactively. Can you check that beta should actually be $\beta = 0.008$ for the plot you want, or should it be 0.08? If it should be 0.08, there is some serious scaling issue happening and I'm not sure _why it would be happening_. The differential equations in R/exposuRe.R are pretty simple.

### With $\beta = 0.08$
![newplot(6)](https://github.com/ashokkrish/episim/assets/51974245/d7f935b9-2fa6-4217-95e2-f0bbffd9e993)

### With $\beta = 0.008$
![newplot(7)](https://github.com/ashokkrish/episim/assets/51974245/5b757015-b76b-4f14-89a4-e8e1a6d5484f)


Otherwise, all should be well and this issue is completed with my latest changes.
