### ISSUE TITLE
Customizable plots 

### ISSUE THREAD

**Issue by Toby-exe** [ashokkrish/episim#93]
Allow user to customize a plots title, line width, colours etc via settings button for each plot that shows a modal with a list of settings

**Comment by Toby-exe** [comment]
@bryce-carson Right now I am working on creating the modal that pops up after the settings button has been clicked and was wondering if my approach was on the right track.

```R
modelResultsPanel <-
  mainPanel(
    id = "outputPanel", style = "display: none;", # Hidden by default
    tabsetPanel(
      id = "tabSet",
      tabPanel(
        "Plot",
        div(
          style = "position: relative;",
          actionButton(
            "plotSettingsButton",
            label = NULL,
            icon = icon("gear"),
            style = plotSettingsButtonStyle
          ),
          plotly::plotlyOutput("modelPlot")
        ),
        uiOutput("modelSubPlots")
      )
.
.
.
rest of modelResultsPanel
```
I created a basic modal just for testing (does nothing) and my understanding is that it should be in ui.R
```R
plotSettingsModal <- modalDialog(
  title = "Plot Settings",
  sliderInput("plotWidth", "Plot Width", 300, 1200, 600),
  sliderInput("plotHeight", "Plot Height", 300, 1200, 600),
  footer = tagList(
    actionButton("closePlotSettings", "Close")
  )
)
```
and the controls (showing or not showing the modal) will be in server.R

```R

  observeEvent(input$plotSettingsButton, {
    showModal(plotSettingsModal)
  })

  observeEvent(input$closePlotSettings, {
    removeModal()
  })
```

but this is not working since plotSettingsModal is not visible/not in scope in server.R I know I have done something wrong but I am not sure what. Or my approach me be wrong entirely.

**Comment by bryce-carson** [comment]
I see. Take a closer look at the packages that offer modal ui components. Good first attempt.

I believe you're on the right track with including the new component in the UI. It might be unnecessary, however. The modal shouldn't need to be built out by us from scratch; plotly probably has something built-in and it should only need minimal integration.

Building the modal from scratch would be the wrong approach.

The way you're showing and hiding the modal is also wrong, insofar as there shouldn't need to be an observer in server.R. Any package wrapping modal ui functionality shouldn't fight us on reactivity; we shouldn't need to watch it for events and trigger redisplay/restyling as in imperative ui programming.

Further reading on what's on offer (packages) will pay off. We're already using bootstrap 5, so there's probably a part of the package we're already using that offers better handling of modals than this solution.

You're close to a solution, so you know. Not a big misstep. The scoping issue could be resolved with show/hide from shinyjs and passing it a css selector or the element id.

Good work on all the plotting stuff. It's paying off and looking good.

**Comment by Toby-exe** [comment]
The reason I had the observe events was because I was using this: https://shiny.posit.co/r/reference/shiny/1.7.3/modaldialog as my reference and in the example where the modal is shown by clicking a button they just use an observeEvent. In fact most of the examples I can find online of how to use shiny's "modalDialog" and "showModal" all seem to just be in the server code. I cant seem to find a solution that does not involve creating most of it from scratch. I checked out cougar stats as well and they seem to have created a custom function called plotOptionsMenuUI(...).

**Comment by bryce-carson** [comment]
Okay. For now it's alright. Move your function to global.R to make it work. Recall that the UI is handled specially upon initialization of Shiny.


The UI file is ran like a script, and its last result is taken as the UI object. That object is converted to HTML and cached for all future connections. The functions defined in the UI file are forgotten once the UI script exits. Functioned defined in that scope are only visible to the running UI generating R process. Functions defined in UI are only accessible from within UI, and only during initialization.

I may do some further reading on this, but taking a look at your reference things seem okay. You shouldn't need to use the observers for closing the modal. The user can close the modal if you give them the easy close option and also a close button within the modal.
