### ISSUE TITLE
Closed population assumption needs to be validated

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#95]
For any deterministic compartmental model without vital dynamics and without the dead (D) compartment there is a closed population assumption. For example, N = S + I + R for an SIR or SIRS model. Same way N = S + E + I + R for an SEIR or SEIRS model.

In these situations our current code doesn't have a **closed population assumption is not validated**. For example I ran SEIR simulation with N = 1, S = 499, E = 0, I = 1, R = 0, m = 25 and the default values for beta, gamma, sigma. This shouldn't even run a simulation to begin with because it doesn't make sense to have a total population of 1 person but 499 of them are susceptible. A validation error needs to be built into the code and a message displayed on the mainPanel().

<img width="664" alt="image" src="https://github.com/ashokkrish/episim/assets/410949/63f32822-a04e-42b2-bae5-b153135adb62">

**Comment by bryce-carson** [comment]
Indeed. TODO.

**Comment by bryce-carson** [comment]
@ashokkrish, I am pushing a commit which I believe closes this issue. The commit _will close_ the issue, but if the change is not satisfactory please reopen the issue and let me know what I missed.
