### ISSUE TITLE
Toggling Vital Dynamics checkBox resets the parameter values

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/episim#99]
I am running a deterministic SIR model and edit the parameter and variable values to something other than the default. Now I click the Vital Dynamics **On**, this resets the parameter and variable values which I previously changed.

This needs to be fixed. Toggling Vital Dynamics on or off should not affect the parameter or variable values.

**Comment by bryce-carson** [comment]
That's true. When I read the code and think about it now, I don't know why I did this "partial reset" before.

```r
  observeEvent(
    { # Any of these three inputs will cause a "partial reset."
      input$stochasticSelect
      input$trueMassAction
      input$vitalDynamics
    },
    isolate(updateNumericInputs(defaults(), session))
```

This entire observable will be removed, fixing this issue.
